kind: 
name: database

steps:
- name: install
  image: blcoccaro/to-deploy:v2
  commands:
  - pwd
  - git clone https://github.com/blcoccaro/runsqlfile.git
  - cd runsqlfile
  - sed -i 's/__SQLFILES__/drone\/\/src\/\/sps\/\/ci/1' config.json
  - sed -i 's/__CNN__/drone\/src\/jsons\/\/cnn.json/1' config.json
  - sed -i 's/__DATABASES__/drone\/\/src\/\/jsons\/\/database.json/1' config.json
  - cat config.json
  - npm install 

trigger:
  branch:
  - master
  event:
  - push