kind: 
name: database

steps:
- name: install
  image: blcoccaro/to-deploy:v2
  commands:
  - git clone https://github.com/blcoccaro/runsqlfile.git
  - cd runsqlfile
  - npm install
  - node index.js

trigger:
  branch:
  - master
  event:
  - push