CREATE PROCEDURE dbo.pr_purchase_get_bin (@id_session VARCHAR(1000))

AS

-- DECLARE @id_session VARCHAR(1000) = 'l01cv1a084d557ll6mdlghdup7'
-- {"bin":"54872"}
SET NOCOUNT ON;

IF OBJECT_ID('tempdb.dbo.#aux', 'U') IS NOT NULL
    DROP TABLE #aux; 

SELECT DISTINCT r.cd_binitau
FROM CI_MIDDLEWAY..MW_EVENTO E
INNER JOIN CI_MIDDLEWAY..MW_APRESENTACAO A ON A.ID_EVENTO = E.ID_EVENTO
INNER JOIN CI_MIDDLEWAY..MW_RESERVA R ON R.ID_APRESENTACAO = A.ID_APRESENTACAO
WHERE R.id_session = @id_session